### ISSUE TITLE
White on white in dark mode?

### ISSUE THREAD

**Issue by yairchu** [projectit-org/ProjectIt-example#14]
The UI opened in dark mode for me by default (perhaps because this is my system setting) and things looked like this:

<img width="418" alt="Screen Shot 2022-07-18 at 11 55 57" src="https://user-images.githubusercontent.com/97606/179477647-b005e38a-2a67-4b56-aa36-8f6428ada184.png">

When I switched to light mode it became more clear so I understood that in Dark mode I wasn't seeing everything:
<img width="256" alt="Screen Shot 2022-07-18 at 11 56 00" src="https://user-images.githubusercontent.com/97606/179477715-4914ed99-d395-496c-8b71-1a2c8d8e5926.png">

**Comment by joswarmer** [comment]
Ah, styling on the dark mode isn't readable.  I'll take a look and see how I can improve it.

**Comment by joswarmer** [comment]
Fixed the dark mode, much of the styling was just missing. It is readable now.
